feat: adds smartrate functionality
EasyPost/easypost-php pull request #104
Opened 2021-05-14 21:14 UTC by Justintime50

Adds the new `/smartrate` endpoint/method on the `Shipment` object.

Simply call `get_smartrates` on the shipment object and you'll be returned a list of smartrates like so:

```json
{
    "result": [
        {
            "carrier": "USPS",
            "carrier_account_id": "ca_123...",
            "created_at": "2021-05-04T21:15:59Z",
            "currency": "USD",
            "delivery_date": null,
            "delivery_date_guaranteed": true,
            "delivery_days": null,
            "est_delivery_days": null,
            "id": "rate_123...",
            "list_currency": null,
            "list_rate": null,
            "mode": "test",
            "object": "Rate",
            "rate": 0.01,
            "retail_currency": null,
            "retail_rate": null,
            "service": "First",
            "shipment_id": "shp_123",
            "time_in_transit": {
                "percentile_50": 2,
                "percentile_75": 3,
                "percentile_85": 4,
                "percentile_90": 4,
                "percentile_95": 4,
                "percentile_97": 4,
                "percentile_99": 4
            },
            "updated_at": "2021-05-04T21:15:59Z"
        },
    ]
}
```

A full code example would look like this:

```python
$shipment = \EasyPost\Shipment::retrieve('shp_123...');
$smartrates = $shipment.get_smartrates();
echo $smartrates;
```

2021-05-14 21:15 UTC, Justintime50 commented on test/EasyPost/Test/ShipmentTest.php
> +        # TODO: Once we've added `php-vcr`, assert that the following values actually match an integer
# Reviewer Note

Without using `php-vcr`, we can't assert the values of these keys match an integer because these values literally change from request to request. For now, asserting they exist.

2021-05-18 19:35 UTC, LoganSimonsen approved these changes
lgtm

2021-05-22 05:03 UTC, jontsai approved these changes
LGTM

2021-06-01 18:14 UTC, jontsai requested changes

2021-06-01 18:14 UTC, jontsai commented on lib/EasyPost/Shipment.php
> +     * @return $this
This comment is off

2021-06-01 18:16 UTC, jontsai submitted a review, later dismissed

2021-06-01 18:19 UTC, jontsai commented on lib/EasyPost/Shipment.php
> +     * @return $response
probably `@return array`

2021-06-01 21:00 UTC, ajnassar submitted a review, later dismissed
LGTM

2021-06-01 22:27 UTC, jontsai submitted a review, later dismissed

2021-06-07 16:31 UTC, Justintime50 commented
> LGTM

@ajnassar looks like you left a comment instead of also approving. Could you re-review and select approve this time? Thanks!

2021-06-07 16:32 UTC, ajnassar approved these changes

2021-06-10 15:43 UTC, merged