fix: corrects JSON encoding for various data types
EasyPost/easypost-php pull request #118
Opened 2021-10-18 23:32 UTC by Justintime50

### Summary

This is an attempt at fixing JSON encoding for various data types. I tried to keep this as least destructive as possible (we could/should be using the `JsonSerializable` interface; however, I didn't want to introduce another larger rewrite if we could for now correct this with a simple pass.

This is accomplished now by:
1. Not using the `array_filter` which had some interesting side effects
2. Making any element that we previously would set as an empty array if no data was present to `null` instead
3. Sending all data as strings (as this was the previous behavior and what almost every field of our API expects)

### Tests

* null tests
* empty string tests
* string tests
* array tests (empty and filled)
* float tests
* integer tests
* boolean tests

I added a few tests to check encoding and updated others. Looking at the output of cassettes, I'm much happier with this approach than the previous as it's behaving much closer to what I'd expect.

Docs about type comparisons: https://www.php.net/manual/en/types.comparisons.php

Closes #117

2021-10-19 00:52 UTC, jontsai commented on lib/EasyPost/Requestor.php
> +        } elseif (is_integer($data)) {
How about `is_numeric` instead?

https://www.php.net/manual/en/function.is-numeric.php

2021-10-19 00:52 UTC, jontsai commented on lib/EasyPost/Requestor.php
> +            $curlOptions[CURLOPT_POSTFIELDS] = json_encode($params);
I think the key observation to make is that `json_encode` happens here, and using the pure PHP built-in (https://www.php.net/manual/en/function.json-encode)

However, I believe, when reading #117, what we might want to do is to implement our own JSON encoder function that will do some pre-treatment to `$params` before passing it into the built-in `json_encode`

I was thinking that we could with your current approach of stringifying all numbers, or define a JSON mapping structure with types.

2021-10-19 00:54 UTC, fiendish commented on lib/EasyPost/Requestor.php
> +        } elseif (is_integer($data)) {
There's already checks for true, false, and array and one that is intended to be for null but which is doing the wrong thing right now. What other types shouldn't all be strvaled?

2021-10-19 01:09 UTC, fiendish commented on lib/EasyPost/Requestor.php
> +            $curlOptions[CURLOPT_POSTFIELDS] = json_encode($params);
I'm not clear on why the param count checks were removed here.

2021-10-19 01:21 UTC, fiendish commented
> We are sending null instead of just dropping keys/objects if the user explicitly passes null. This is probably an acceptable behavior; however, we may want to simply drop them altogether?

It wouldn't hurt to throw a null key check inside the is_array foreach before recursing.

Like, if we're only looking for strval conversion here and not yet applying more explicit field type checks, maybe (keeping the param count > 0 checks later on instead of removing them)...
```
@@ -55,11 +55,9 @@
      */
     private static function _encodeObjects($data)
     {
-        if (!$data) {
-            $data = array();
-        }
-
-        if ($data instanceof EasypostResource) {
+        if (is_null($data)) {
+            return array();
+        } elseif ($data instanceof EasypostResource) {
             return array("id" => self::utf8($data->id));
         } elseif ($data === true) {
             return 'true';
@@ -68,12 +66,14 @@
         } elseif (is_array($data)) {
             $resource = array();
             foreach ($data as $k => $v) {
-                $resource[$k] = self::_encodeObjects($v);
+                if (!is_null($v)) {
+                    $resource[$k] = self::_encodeObjects($v);
+                }
             }
 
             return array_filter($resource);
         } else {
-            return self::utf8($data);
+            return self::utf8(strval($data));
         }
     }
```
Though I didn't test it

2021-10-19 16:02 UTC, fiendish commented on lib/EasyPost/Requestor.php
> +            $curlOptions[CURLOPT_POSTFIELDS] = json_encode($params);
Makes sense!

2021-10-19 16:44 UTC, fiendish requested changes
√

2021-10-19 16:44 UTC, fiendish commented on lib/EasyPost/Requestor.php
>              }
I just realized that this empty array null return kinda contradicts `is_null($data)` returning an empty array above. Like, if the caller passes null it gets back an empty array, and if the caller passes an empty array it gets back null. 🤕 

I think this wants to only happen for nested layers, in which case probably it should go next to `!is_null($v)` in the foreach?

2021-10-19 16:51 UTC, Justintime50 commented on lib/EasyPost/Requestor.php
>              }
Ah, great call! This is evident in an empty `customs_items` null instead of an empty array. Fixed!

2021-10-19 17:02 UTC, fiendish commented on lib/EasyPost/Requestor.php
> +                } elseif (!is_null($v)) {
Compound logic like this is a bit ugly, but I think in this form it would be more like
```suggestion
                if (!is_null($v)) and ($v !== "") and (!is_array($v) or !empty($v)) {
```

2021-10-20 01:02 UTC, jontsai approved these changes

2021-10-20 01:09 UTC, fiendish commented on lib/EasyPost/Requestor.php
> +            $absUrl = "$absUrl?$urlParams";
Agreed

2021-10-20 17:18 UTC, jontsai approved these changes

2021-10-20 19:39 UTC, merged