chore: use stronger test assertions where possible
EasyPost/easypost-php pull request #140
Opened 2022-02-23 20:14 UTC by Justintime50

Uses stronger test assertions where possible, brought up by @jchen293 where these should have been written this way but were overlooked.

2022-02-23 23:32 UTC, jchen293 requested changes

2022-02-23 23:32 UTC, jchen293 commented on test/EasyPost/RefundTest.php
> +        $this->assertEquals($refunds['refunds'][0]->id, $retrieved_refund->id);
We should able to compare objects for **testRetrieve()** in RefundTest. I was able to compare objects in Java.
```suggestion
        $this->assertEquals($refunds['refunds'][0], $retrieved_refund);
```

2022-02-23 23:32 UTC, jchen293 commented on test/EasyPost/ReportTest.php
> +        $report = Report::create([
I would undo this change, so we can make the variable name more explicit.

2022-02-23 23:32 UTC, jchen293 commented on test/EasyPost/ReportTest.php
> +    public function testRetrievePaymentLogReport($report)
Same here, some people might be confused on which **`report`** variable is this refers to.

2022-02-23 23:34 UTC, Justintime50 commented on test/EasyPost/ReportTest.php
> +        $report = Report::create([
This shouldn't matter because we are only testing one report per test, the type of the report is inherent. The name of report is also in the test name.

Having them more explicit would make sense if we had multiple reports in the same scope but we don't here.

2022-02-23 23:35 UTC, Justintime50 commented on test/EasyPost/ReportTest.php
> +    public function testRetrievePaymentLogReport($report)
I don't believe this is a problem because we specify `@depends testCreatePaymentLogReport` 2 lines above and the name of the test is `testRetrievePaymentLogReport`, they match up already.

2022-02-23 23:37 UTC, Justintime50 commented on test/EasyPost/RefundTest.php
> +        $this->assertEquals($refunds['refunds'][0]->id, $retrieved_refund->id);
I tried this one here but wasn't able to make it work due to how PHP's VCR works.

2022-02-23 23:38 UTC, jchen293 commented on test/EasyPost/ReportTest.php
> +    public function testRetrievePaymentLogReport($report)
I won't block it, but for readability, I prefer a variable name that is explicit.

2022-02-23 23:39 UTC, jchen293 submitted a review, later dismissed

2022-02-24 20:22 UTC, nwithan8 commented
This might be the right ticket to bring this up on:
https://github.com/EasyPost/easypost-php/blob/master/test/EasyPost/CarrierAccountTest.php#L75
We should be comparing the retrieved carrier account and the original carrier account (or at least the IDs of each), a la https://github.com/EasyPost/easypost-php/blob/master/test/EasyPost/AddressTest.php#L90

2022-02-24 21:35 UTC, Justintime50 commented
@nwithan8 indeed, I've corrected that.

2022-02-24 22:20 UTC, nwithan8 submitted a review, later dismissed

2022-02-24 23:09 UTC, jchen293 requested changes

2022-02-24 23:09 UTC, jchen293 commented on test/EasyPost/ScanFormTest.php
> +        $this->assertStringMatchesFormat($scanform, $retrieved_scanform);
The assertion here is wrong, it should be assertEquals()
```suggestion
        $this->assertEquals($scanform, $retrieved_scanform);
```

2022-02-24 23:09 UTC, jchen293 commented on test/EasyPost/UserTest.php
> +        $this->assertEquals($user->name, 'Test User');
Order is wrong here.
```suggestion
        $this->assertEquals('Test User', $user->name);
```

2022-02-24 23:13 UTC, Justintime50 commented on test/EasyPost/ScanFormTest.php
> +        $this->assertStringMatchesFormat($scanform, $retrieved_scanform);
Nice catch.

2022-02-24 23:23 UTC, jchen293 approved these changes

2022-02-25 00:10 UTC, nwithan8 commented
Caught another one: https://github.com/EasyPost/easypost-php/blob/master/test/EasyPost/InsuranceTest.php#L76

2022-02-25 00:22 UTC, Justintime50 commented
@nwithan8 that should have been fixed in this PR already. The link you gave is for the master branch, not this PR.

2022-02-25 18:10 UTC, nwithan8 approved these changes

2022-02-25 18:10 UTC, merged