[feat] Support for `columns` and `additional_columns` on Report creation
EasyPost/easypost-php pull request #145
Opened 2022-03-22 21:49 UTC by nwithan8

This PR:
- Adds support for specifying `columns` and `additional_columns` (both lists of strings) in the parameters dictionary passed into the `Report->create()` function.

Unfortunately, since the API response does not indicate the columns used for a report, the only way to ensure the report actually includes the columns requested would be to make a live API call, download the generated CSV report and parse its column headers. That is a complex unit test with many points of failure and prevents us from using VCR.

Instead, we simply assume that if no error is thrown during the API call to generate and retrieve the report, that the report contains the correct columns. If it doesn't, that constitutes a server-side error that is out of our control.

2022-03-22 22:30 UTC, jchen293 commented on lib/EasyPost/Report.php
> +                    $urlMod .= "additional_columns[]=" . $additional_column . "&";
this `urlMod` is not being used anywhere, shouldn't this `urlMod replace the `url` when making the request call?

2022-03-22 22:39 UTC, Justintime50 requested changes

2022-03-22 22:39 UTC, Justintime50 commented on lib/EasyPost/Report.php
> +                    $urlMod .= "additional_columns[]=" . $additional_column . "&";
Jack is correct, this isn't getting used and should be `$url`, please re-record the cassettes to ensure this worked.

2022-03-22 22:39 UTC, Justintime50 commented on lib/EasyPost/Report.php
> +        if ((isset($params['columns']) && is_array($params['columns'])) || (isset($params['additional_columns']) && is_array($params['additional_columns']))) {
There is too much nesting here. These should be individual if statements and not using the `||` operator since they should be mutually exclusive. Two blocks of code, one for `columns` and one for `additional_columns`.

2022-03-22 22:39 UTC, Justintime50 commented on lib/EasyPost/Report.php
> +            if (isset($params['columns'])) {
Per my comment above, if we split these into separate blocks, there will be no need to run multiple if statements since it will no longer be nested.

2022-03-22 22:39 UTC, Justintime50 commented on test/EasyPost/ReportTest.php
> +        // Verify parameters sent correctly by checking the URL in the cassette.
Please move this above the assertion. Code that's sitting by itself without being attached to anything is confusing. Having it above will help explain why there's only a single assertion and prompt users to go elsewhere to find more data.

2022-03-22 22:39 UTC, Justintime50 commented on test/EasyPost/ReportTest.php
> +        // Verify parameters sent correctly by checking the URL in the cassette.
Comment above.

2022-03-22 23:25 UTC, nwithan8 commented on test/EasyPost/ReportTest.php
> +        // Verify parameters sent correctly by checking the URL in the cassette.
Resolved in e97ee36e508d4a6395d03c8575079749f3aec069

2022-03-22 23:25 UTC, nwithan8 commented on test/EasyPost/ReportTest.php
> +        // Verify parameters sent correctly by checking the URL in the cassette.
Resolved in e97ee36e508d4a6395d03c8575079749f3aec069

2022-03-22 23:25 UTC, nwithan8 commented on lib/EasyPost/Report.php
> +            if (isset($params['columns'])) {
Resolved in e97ee36e508d4a6395d03c8575079749f3aec069

2022-03-22 23:25 UTC, nwithan8 commented on lib/EasyPost/Report.php
> +        if ((isset($params['columns']) && is_array($params['columns'])) || (isset($params['additional_columns']) && is_array($params['additional_columns']))) {
Was modeling after our Address verification setup.
Resolved in e97ee36e508d4a6395d03c8575079749f3aec069

2022-03-22 23:25 UTC, nwithan8 commented on lib/EasyPost/Report.php
> +                    $urlMod .= "additional_columns[]=" . $additional_column . "&";
Resolved in e97ee36e508d4a6395d03c8575079749f3aec069

2022-03-23 15:51 UTC, Justintime50 requested changes

2022-03-23 15:51 UTC, Justintime50 commented on lib/EasyPost/Report.php
> +        $type = $params['type'];
This doesn't really help since it's only being used once, there is no need for the intermediate variable and instead could just be used inline in the `$url` var below OR this could come above line ~70 and reused in that if check which would make sense to have a var since it would then be used twice.

2022-03-23 15:51 UTC, Justintime50 commented on lib/EasyPost/Report.php
> +            unset($params['columns']);
Please add a comment as to why we are unsetting these here

2022-03-23 15:51 UTC, Justintime50 commented on lib/EasyPost/Report.php
> +        }
Why do this instead of just appending to the already existent `$url`?

2022-03-23 17:12 UTC, nwithan8 commented on lib/EasyPost/Report.php
> +        }
Addressed in 6d220378d34ba8ed3dccaab89bb5493dddd7a2c4

2022-03-23 17:12 UTC, nwithan8 commented on lib/EasyPost/Report.php
> +            unset($params['additional_columns']);
6d220378d34ba8ed3dccaab89bb5493dddd7a2c4

2022-03-23 17:12 UTC, nwithan8 commented on lib/EasyPost/Report.php
> +            unset($params['columns']);
6d220378d34ba8ed3dccaab89bb5493dddd7a2c4

2022-03-23 17:13 UTC, nwithan8 commented on lib/EasyPost/Report.php
> +        $type = $params['type'];
Addressed in 6d220378d34ba8ed3dccaab89bb5493dddd7a2c4

2022-03-23 18:26 UTC, merged