add PULL_REQUEST_TEMPLATE file.
EasyPost/easypost-php pull request #156
Opened 2022-04-11 20:22 UTC by jchen293

This PR adds the pull request template.

2022-04-11 20:49 UTC, Justintime50 submitted a review, later dismissed

2022-04-11 20:49 UTC, Justintime50 commented on .github/PULL_REQUEST_TEMPLATE.md
> +Please provide a general summary of your PR changes in here and link any related issues or other pull requests.
This should be a comment instead of plain-text. That way if the user accidentally keeps this in here, it won't show up in the actual issue.

2022-04-11 20:49 UTC, Justintime50 commented on .github/PULL_REQUEST_TEMPLATE.md
> +Please provide a detail how did you test this pull request, see below testing requirement for more information.
```suggestion
Please provide details on how you tested this code, see below testing requirement for more information.
```

2022-04-11 20:49 UTC, Justintime50 commented on .github/PULL_REQUEST_TEMPLATE.md
> +# How did you test the Pull Request?
Thoughts on simply calling it `Testing`?

```suggestion
# Testing
```

2022-04-11 20:49 UTC, Justintime50 commented on .github/PULL_REQUEST_TEMPLATE.md
> +The only time a test is not necessary is for things like updating the README or other config files
This should be a list for easier reading. It should also be a comment so that if they submit without deleting this we don't have to read all this as well.

2022-04-11 21:00 UTC, jchen293 commented on .github/PULL_REQUEST_TEMPLATE.md
> +# How did you test the Pull Request?
I agree since we already have a description.

2022-04-11 21:37 UTC, nwithan8 requested changes

2022-04-11 21:37 UTC, nwithan8 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc...)
nit: don't need ...

2022-04-11 21:37 UTC, nwithan8 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!--- Please provide a general summary of your PR changes in here and link any related issues or other pull requests. -->
nit: remove "in here"

2022-04-11 21:37 UTC, nwithan8 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!--- Please provide details on how you tested this code, see below testing requirement for more information.
nit: "how you tested this code. See below"

2022-04-11 21:37 UTC, nwithan8 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- All pull requests must be tested (unit tests where possible with accompanying cassettes, provide a screenshot of End-to-End testing is a must when unit tests are not possible)
```suggestion
- All pull requests must be tested (unit tests where possible with accompanying cassettes, or provide a screenshot of end-to-end testing when unit tests are not possible)
```

2022-04-11 21:37 UTC, nwithan8 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- The only time a test is not necessary is for things like updating the README or other config files --->
```suggestion--->
```

2022-04-12 15:46 UTC, Justintime50 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc...)
@nwithan8 are you suggesting this whole checkbox section isn't needed?

2022-04-12 15:48 UTC, Justintime50 commented on .github/PULL_REQUEST_TEMPLATE.md
> +Please select option(s) that is relevant to this PR.
```suggestion
Please select the option(s) that are relevant to this PR.
```

2022-04-12 15:49 UTC, Justintime50 commented on .github/PULL_REQUEST_TEMPLATE.md
> +# Type of change
```suggestion
# Pull Request Type
```

2022-04-12 15:49 UTC, Justintime50 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- Bug fixes/refactors must re-record existing cassettes -->
We could probably move these multi lines like this?

```suggestion
<!--
Please provide details on how you tested this code. See below.

- All pull requests must be tested (unit tests where possible with accompanying cassettes, or provide a screenshot of end-to-end testing when unit tests are not possible)
- New features must get a new unit test
- Bug fixes/refactors must re-record existing cassettes
-->
```

2022-04-12 16:04 UTC, jchen293 commented on .github/PULL_REQUEST_TEMPLATE.md
> +Please select option(s) that is relevant to this PR.
resolved

2022-04-12 16:04 UTC, jchen293 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- Bug fixes/refactors must re-record existing cassettes -->
resolved

2022-04-12 16:05 UTC, nwithan8 submitted a review, later dismissed

2022-04-12 16:06 UTC, jchen293 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Please provide details on how you tested this code. See below.
resolved

2022-04-12 16:11 UTC, nwithan8 approved these changes

2022-04-12 16:13 UTC, merged