remove additional code that add params to URL query for post method.
EasyPost/easypost-php pull request #157
Opened 2022-04-13 21:35 UTC by jchen293

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

# Description

This PR removes code that adds `strict` and `verify_strict` to the URL query when the API method is POST. The `wrappedParams` is also removed since it does not do anything.

# Testing

re-record existing cassettes and all unit tests passed.

2022-04-13 21:39 UTC, Justintime50 requested changes

2022-04-13 21:39 UTC, Justintime50 commented on test/cassettes/shipments/createWithIds.yml
> -            location: /api/v2/parcels.prcl_3274f0f657194a8893c6e5da7aa8cd5e
Hmm... this should be a `/` not a `.`, can we look into this?

2022-04-13 21:39 UTC, Justintime50 commented on lib/EasyPost/Address.php
> -        }
This still needs to be here. Basically it's a convenience for the user if they don't wrap their params in `address`, we'll do it for them.

2022-04-13 21:43 UTC, jchen293 commented on lib/EasyPost/Address.php
> -        }
I just removed it from Java lib, the API endpoint still takes the param if it's not wrapped in `address`.

2022-04-14 18:33 UTC, Justintime50 commented on lib/EasyPost/Address.php
> -        }
Yeah we definitely need this.

Additionally we need to ensure the `verify` and `verify_strict` params are at the top level outside of `address`.

2022-04-14 18:33 UTC, Justintime50 commented on test/cassettes/shipments/createWithIds.yml
> -            location: /api/v2/parcels.prcl_3274f0f657194a8893c6e5da7aa8cd5e
I briefly looked at this cursed problem... can't determine why it's showing up like this but it's working as intended.

2022-04-14 18:35 UTC, Justintime50 commented
Please also remove the following block of code in the `verify` function that accidentally got skipped (since it's related):

```php
            if (!empty($response['message'])) {
                $verified_address->message = $response['message'];
                $verified_address->_immutableValues[] = 'message';
            }
```

2022-04-14 18:59 UTC, jchen293 commented on lib/EasyPost/Address.php
> -        }
I have added this back

2022-04-14 19:23 UTC, Justintime50 requested changes

2022-04-14 19:23 UTC, Justintime50 commented on lib/EasyPost/Address.php
> +        if ((isset($params['address']['verify']) && is_array($params['address']['verify']))) {
This should be checking for the `verify` and `verify_strict` params at the root level and not nested in `address`.

2022-04-14 19:56 UTC, jchen293 commented on lib/EasyPost/Address.php
> +        if ((isset($params['address']['verify']) && is_array($params['address']['verify']))) {
What I have should be correct. I am checking `verify` and `verify_strict` in `address` which is nested, see lines 61 - 64.

2022-04-14 21:35 UTC, Justintime50 submitted a review, later dismissed

2022-04-14 21:35 UTC, Justintime50 commented on lib/EasyPost/Address.php
> +        if ((isset($params['address']['verify']) && is_array($params['address']['verify']))) {
Not quite.

Lines 61-65 above are a convenience to wrap the parameters in `address` **only if the user didn't already do this**. What we should be doing is checking if the `params` have a direct key of `verify` and `verify_strict` as it should not be nested inside of an `address` key inside of params. We want the check to be up one level. For instance, in the Java/Ruby PRs you just put up which are done correctly, you aren't checking for `verify` inside of `address`, you are looking for it at the root of `params` which is the change we need to also make here.

2022-04-14 21:35 UTC, Justintime50 commented on lib/EasyPost/Address.php
> -            if (!empty($response['message'])) {
Thanks!

2022-04-14 21:42 UTC, jchen293 commented on lib/EasyPost/Address.php
> +        if ((isset($params['address']['verify']) && is_array($params['address']['verify']))) {
I think either way should work, Java/Ruby checks `verify` and `verify_strict` before the wrapper but PHP is after. I will change the code to stay consistent.

2022-04-14 21:45 UTC, Justintime50 commented on lib/EasyPost/Address.php
> +        if ((isset($params['address']['verify']) && is_array($params['address']['verify']))) {
It "works" now because of the way we are passing the data in; however, this will break for some customers. We should take the most generic/safest route. If you look at how the code used to work before these changes, you'll notice that they are doing what I'm suggesting: `$params['verify']`, etc.

2022-04-14 21:57 UTC, jchen293 commented on lib/EasyPost/Address.php
> +        if ((isset($params['address']['verify']) && is_array($params['address']['verify']))) {
There is `unset` which removes the `verify` and `verify_strict` inside of `address`, `verify` and `verify_strict` will be added in the top-level param.

2022-04-14 23:33 UTC, nwithan8 approved these changes
lgtm

2022-04-15 04:55 UTC, Justintime50 requested changes
We shouldn't need these extra brackets.

2022-04-15 04:55 UTC, Justintime50 commented on lib/EasyPost/Address.php
> +        if ((isset($params['verify']) && is_array($params['verify']))) {
```suggestion
        if (isset($params['verify'] && is_array($params['verify'])) {
```

2022-04-15 04:55 UTC, Justintime50 commented on lib/EasyPost/Address.php
> +        if ((isset($params['verify_strict']) && is_array($params['verify_strict']))) {
```suggestion
        if (isset($params['verify_strict']) && is_array($params['verify_strict'])) {
```

2022-04-15 15:24 UTC, jchen293 commented on lib/EasyPost/Address.php
> +        if ((isset($params['verify']) && is_array($params['verify']))) {
resolved

2022-04-15 15:24 UTC, jchen293 commented on lib/EasyPost/Address.php
> +        if ((isset($params['verify_strict']) && is_array($params['verify_strict']))) {
resolved

2022-04-15 16:01 UTC, Justintime50 approved these changes

2022-04-15 16:02 UTC, nwithan8 approved these changes

2022-04-15 16:06 UTC, merged