- Adds the  Beta class with , , , and  functions.
EasyPost/easypost-php pull request #167
Opened 2022-05-12 23:34 UTC by jchen293

# Description

Do not code review this PR yet.

# Testing

Add unit tests

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2022-05-13 17:54 UTC, Justintime50 approved these changes

2022-05-13 18:10 UTC, nwithan8 requested changes

2022-05-13 18:10 UTC, nwithan8 commented on lib/EasyPost/Beta/EndShipper.php
> +        return $this->_save('EasyPost\Address', true);
Are we still using Address, or are we making a standalone EndShipper object, per our internal conversation today?

2022-05-13 18:15 UTC, jchen293 commented on lib/EasyPost/Beta/EndShipper.php
> +        return $this->_save('EasyPost\Address', true);
This is something else that has to do with the API endpoint. The `EndShipper update endpoint` accepts `address` in the parameter instead of `end_shipper`. Nothing has to do with the conversation today.

2022-05-13 18:22 UTC, Justintime50 commented on lib/EasyPost/Beta/EndShipper.php
> +        return $this->_save('EasyPost\Address', true);
Ha yeah, we dynamically determine the endpoint to hit based on the class name. All others pass in the `get_class()` function but here we need to specify the Address class so that it properly wraps all the params in `address` instead of `end_shipper` per the docs.

2022-05-13 18:29 UTC, nwithan8 approved these changes

2022-05-17 19:36 UTC, Justintime50 approved these changes

2022-05-17 19:36 UTC, Justintime50 commented on test/EasyPost/Beta/EndShipperTest.php
> +        $end_shipper->email = 'test@example.com';
Nit: We could have reassigned these to the individual fixture values for each field so we didn't need to reuse these values.

2022-05-17 19:50 UTC, merged