Add generate forms functionality
EasyPost/easypost-php pull request #193
Opened 2022-07-11 20:24 UTC by nwithan8

# Description

- Add form creation function on Shipment
- Add unit test and cassette for form creation
- Update CHANGELOG.md

# Testing

- [x] New unit test and cassette
- [x] All tests pass as expected

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2022-07-11 20:26 UTC, Justintime50 approved these changes

2022-07-11 21:08 UTC, Justintime50 approved these changes

2022-07-12 15:30 UTC, jchen293 requested changes

2022-07-12 15:30 UTC, jchen293 commented on CHANGELOG.md
> +- Add form creation via `generate_form()` function on a `Shipment` object
We already released these. You need to add this bullet to `Next Release` section

2022-07-12 15:30 UTC, jchen293 commented on lib/EasyPost/Shipment.php
> +    public function generate_form(string $formType, $formOptions = null): Shipment
The return type of this function can also be `void` since we are updating the shipment object value in place.

2022-07-12 15:30 UTC, jchen293 commented on test/EasyPost/ShipmentTest.php
> +     */
Incomplete docstring

2022-07-12 17:06 UTC, nwithan8 commented on lib/EasyPost/Shipment.php
> +    public function generate_form(string $formType, $formOptions = null): Shipment
The function is always returning a `Shipment` object (it just happens to be the same Shipment object that you're calling this function against). As a result, it's up to the user whether they want to capture the return value. but the return value isn't `void`

2022-07-12 17:08 UTC, nwithan8 commented on test/EasyPost/ShipmentTest.php
> +     */
Resolved

2022-07-12 17:08 UTC, nwithan8 commented on CHANGELOG.md
> +- Add form creation via `generate_form()` function on a `Shipment` object
Resolved

2022-07-12 17:36 UTC, Justintime50 approved these changes

2022-07-12 19:10 UTC, jchen293 approved these changes

2022-07-12 19:21 UTC, merged