[WIP] add helper function to validate a webhook that is originated from Eas…
EasyPost/easypost-php pull request #200
Opened 2022-07-22 21:15 UTC by jchen293

…yPost

# Description

[WIP] Adds a helper function to validate if a webhook originated from EasyPost with the stored Webhook secret.

# Testing

Add a unit test

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2022-07-22 21:25 UTC, Justintime50 commented on lib/EasyPost/Webhook.php
> +    public static function validateWebhook($webhook_body, $headers, $webhook_secret)
Function params also need to be camel cased (the rest will get updated in the rewrite)

```suggestion
    public static function validateWebhook($webhookBody, $headers, $webhookSecret)
```

2022-07-22 21:30 UTC, jchen293 commented on lib/EasyPost/Webhook.php
> +    public static function validateWebhook($webhook_body, $headers, $webhook_secret)
It's still in progress, I will correct this

2022-07-27 21:30 UTC, Justintime50 requested changes

2022-07-27 21:30 UTC, Justintime50 commented on lib/EasyPost/Webhook.php
> +            $encodedSecret = mb_convert_encoding(utf8_encode($normalizedSecret), "ISO-8859-1", "UTF-8");
This still isn't perfectly ideal as there could be slight alterations depending on the input. Let's fix it to be uniform with the other libraries.
```suggestion
            $encodedSecret = mb_convert_encoding($normalizedSecret, 'UTF-8');
```

2022-07-27 23:04 UTC, jchen293 commented on test/EasyPost/WebhookTest.php
> +     * @return void
FYI, all of the unit tests have a return type in the docstring.

2022-07-27 23:13 UTC, Justintime50 commented on test/EasyPost/WebhookTest.php
> +     * @return void
Indeed they do. Can you add an internal task to remove these? They shouldn't be needed for a test context.

2022-07-28 15:42 UTC, jchen293 commented on lib/EasyPost/Webhook.php
> +            $encodedSecret = mb_convert_encoding(utf8_encode($normalizedSecret), "ISO-8859-1", "UTF-8");
fixed

2022-07-28 15:58 UTC, Justintime50 approved these changes

2022-07-28 17:28 UTC, nwithan8 approved these changes

2022-07-28 19:40 UTC, merged