New test utility to mock HTTP requests/responses
EasyPost/easypost-php pull request #246
Opened 2022-12-15 22:24 UTC by nwithan8

# Description

Based on the implementation in [C#](https://github.com/EasyPost/easypost-csharp/blob/master/EasyPost.Tests/ServicesTests/BillingServiceTest.cs#L21), [Go](https://github.com/EasyPost/easypost-go/pull/137) and [Node](https://github.com/EasyPost/easypost-node/pull/317), this adds the ability to mock requests.

This is accomplished by adding a `MockUtility`object into the EasyPost client. If this property is set, the client will ONLY use mock requests (any request passed in that is not a configured mock request will throw an exception).

# Testing
- Use mocking in new billing tests
<img width="513" alt="image" src="https://user-images.githubusercontent.com/17054780/207980101-cd1e6d13-1375-478d-b588-b143fff00c62.png">

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2022-12-15 22:46 UTC, Justintime50 requested changes

2022-12-15 22:46 UTC, Justintime50 commented on lib/EasyPost/Http/Requestor.php
> +                throw new HttpException("No matching mock request found for {$method} {$absoluteUrl}");
This error message needs to be a constant

2022-12-15 22:46 UTC, Justintime50 commented on test/EasyPost/BillingTest.php
> +use EasyPost\Test\mocking\MockRequestResponseInfo;
PHP folders must be title cased.

2022-12-15 22:46 UTC, Justintime50 commented on README.md
> +Some of our unit tests require HTTP calls that cannot be easily tested with live/recorded calls (e.g. HTTP calls that
As mentioned before, please match the current styling of the document which is not to break up paragraphs on newlines if they are too long.

2022-12-15 22:46 UTC, Justintime50 commented on README.md
> +At the time to make a real HTTP request, a mock client will instead check which mock request entry matches the queued
```suggestion
At the time of making a real HTTP request, a mock client will instead check which mock request entry matches the queued
```

2022-12-15 22:46 UTC, Justintime50 commented on README.md
> +use EasyPost\Test\mocking\MockRequestResponseInfo;
Must be `Mocking`

2022-12-15 22:46 UTC, Justintime50 commented on lib/EasyPost/EasyPostClient.php
> +    public function __construct($apiKey, $timeout = Constants::TIMEOUT, $apiBase = Constants::API_BASE, $mockingUtility = null)
Shouldn't the default be `false`?

2022-12-15 22:46 UTC, Justintime50 commented on lib/EasyPost/EasyPostClient.php
> +        return $this->mockingUtility !== null;
I would expect we'd just to make sure this isn't false.

2022-12-15 22:46 UTC, Justintime50 commented on test/EasyPost/BillingTest.php
> +    }
This code does nothing, please remove it.

2022-12-15 22:46 UTC, Justintime50 commented on test/EasyPost/BillingTest.php
> +    public static function getClient(MockingUtility $mockUtility = null): \EasyPost\EasyPostClient
We don't use type hints in this library yet, please don't add them one-off. 

Additionally, we need to `use` or import everything at the top level. This helps readers know exactly what is used in this file right when opening it. We shouldn't mix imports at the top and explicit calls inline later down the file.

2022-12-15 22:46 UTC, Justintime50 commented on test/EasyPost/BillingTest.php
> +    }
The docstring for this was copy/pasted and never updated.

Even still, this function isn't needed if convention is followed. PHPUnit already allows for a `setUpBeforeClass` function which is where you should be setting up the global client for this test file. Please follow the pattern established for all the previous tests.

2022-12-15 22:46 UTC, Justintime50 commented on test/EasyPost/BillingTest.php
> +     * @throws MissingParameterException
There is no need to annotate tests with `throws` tags

2022-12-15 22:46 UTC, Justintime50 commented on test/EasyPost/BillingTest.php
> +            $this->assertTrue(true);
Question: I'd expect we could assert the URL getting hit here. How would this ever throw an error?

2022-12-15 22:46 UTC, Justintime50 commented on test/EasyPost/BillingTest.php
> +    public function testFundWalletWithNoPriorityLevel()
These functions all need docblocks

2022-12-15 22:46 UTC, Justintime50 commented on test/EasyPost/BillingTest.php
> +        $this->assertNotNull($paymentMethodSummary);
Separate code from assertions with a line break.

2022-12-15 22:46 UTC, Justintime50 commented on test/EasyPost/BillingTest.php
> +     * @throws PaymentException
Replace throws with a human readable sentence describing what this test does, see other libs for an example.

This is true of all the docblocks here. We shouldn't annotate errors thrown in tests because they could change and it's misleading because it tells the user it's important to this test when it isn't. Additionally, this test function does not throw anything at all. Only functions that physically throw an exception should be annotated as such.

2022-12-15 22:46 UTC, Justintime50 commented on test/EasyPost/BillingTest.php
> +        // The payment method is not exposed by this method, so we can't assert against it. If this test doesn't throw an exception, it worked (see test below)
This should be a note in a docblock with the first sentence describing the test itself.

2022-12-15 22:46 UTC, Justintime50 commented on test/EasyPost/mocking/MockingUtility.php
> +            $urlMatches = $mockRequest->matchRule->urlRegexPattern == '' || preg_match($mockRequest->matchRule->urlRegexPattern, $url) >= 1;  // limit to exactly one match?
Why a question mark?

2022-12-15 22:47 UTC, Justintime50 commented
Please also provide a screenshot showing that test coverage includes these lines of code. I'm glad the tests pass, but if the tests don't actually run the code in question then this adds no benefit.

2022-12-15 22:49 UTC, nwithan8 commented on lib/EasyPost/EasyPostClient.php
> +    public function __construct($apiKey, $timeout = Constants::TIMEOUT, $apiBase = Constants::API_BASE, $mockingUtility = null)
It's an object, not a boolean

2022-12-15 22:49 UTC, nwithan8 commented on lib/EasyPost/EasyPostClient.php
> +        return $this->mockingUtility !== null;
It's an object, not a boolean

2022-12-15 22:51 UTC, nwithan8 commented on test/EasyPost/BillingTest.php
> +            $this->assertTrue(true);
If the HTTP request (a real one) were to throw an exception. Crafting the test like it's making real requests (see webhook delete test)

2022-12-15 23:40 UTC, nwithan8 commented on test/EasyPost/BillingTest.php
> +    }
This is used to set the global client.
Some tests however need to set up a local client with specific mock requests override, which is what this function is for.

2022-12-15 23:46 UTC, nwithan8 commented on test/EasyPost/BillingTest.php
> +    public function testFundWalletWithNoPriorityLevel()
Alright, I figured the function names were self-explanatory.

2022-12-15 23:50 UTC, nwithan8 commented
> Please also provide a screenshot showing that test coverage includes these lines of code. I'm glad the tests pass, but if the tests don't actually run the code in question then this adds no benefit.

`make coverage`:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/17054780/207990614-b3a2d6e0-f1a1-4fcc-9ed6-e0234f79ba91.png">

2022-12-16 16:44 UTC, Justintime50 commented
This screenshot still doesn't show the percentage coverage and if it went up from the previous number. Either find the coverage percentage on the CLI and ensure it's at least a full point or more above the minimum or open the coverage HTML report and screenshot/verify that.

2022-12-16 19:51 UTC, Justintime50 submitted a review, later dismissed
Please bump the minimum coverage number found in the Makefile

2022-12-16 19:55 UTC, Justintime50 approved these changes

2022-12-16 20:16 UTC, jchen293 approved these changes

2022-12-16 20:17 UTC, merged