feat: carrier metadata GA
EasyPost/easypost-php pull request #294
Opened 2023-05-31 20:52 UTC by Justintime50

# Description

In PHP, I incorrectly added this initially without the beta namespace. This PR simply updates the endpoint and corrects a couple names

# Testing

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2023-05-31 20:54 UTC, jchen293 approved these changes

2023-05-31 21:43 UTC, nwithan8 requested changes

2023-05-31 21:43 UTC, nwithan8 commented on lib/EasyPost/Service/CarrierMetadataService.php
> +        $url = '/metadata/carriers';
The URL changed?

2023-05-31 21:49 UTC, Justintime50 commented on lib/EasyPost/Service/CarrierMetadataService.php
> +        $url = '/metadata/carriers';
Yes, late feedback internally

2023-06-01 18:26 UTC, nwithan8 approved these changes

2023-06-01 20:46 UTC, merged