fix: pagination errors with user-supplied params
EasyPost/easypost-php pull request #316
Opened 2023-11-21 23:17 UTC by Justintime50

# Description

# Testing

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2023-11-27 14:43 UTC, nwithan8 requested changes

2023-11-27 14:43 UTC, nwithan8 commented on lib/EasyPost/Service/ReportService.php
> +        $url = self::reportUrl($reportArray[0]->object);
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** ‏ Can you explain how this `reportUrl` function works? What is `object` in this situation?

2023-11-27 17:05 UTC, Justintime50 commented on lib/EasyPost/Service/ReportService.php
> +        $url = self::reportUrl($reportArray[0]->object);
object is the type of report. The code before wouldn't actually pass in anything it could use haha. This will pass in something like `ShipmentReport` and will turn it into `shipment`

2023-11-27 19:12 UTC, dcaballeroc reviewed
Update pertinent cassettes as well?

2023-11-28 17:20 UTC, dcaballeroc approved these changes

2023-11-28 19:28 UTC, nwithan8 approved these changes

2023-11-28 19:31 UTC, merged